name: etl-pdf-pipeline
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - deprecated=1.2.13=py313hecd8cb5_0
  - expat=2.7.1=h6d0c2b6_0
  - filelock=3.17.0=py313hecd8cb5_0
  - fsspec=2025.7.0=py313h653c010_0
  - gmp=6.3.0=h6d0c2b6_0
  - gmpy2=2.2.1=py313h2cec913_0
  - importlib-metadata=8.5.0=py313hecd8cb5_0
  - jinja2=3.1.6=py313hecd8cb5_0
  - libabseil=20250127.0=cxx17_h548131f_0
  - libcxx=19.1.7=haebbb44_3
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libmpdec=4.0.0=h46256e1_0
  - libopenblas=0.3.29=h3f8574a_0
  - libprotobuf=5.29.3=h66a43dd_1
  - libtorch=2.6.0=cpu_openblas_h4faba3d_6
  - libuv=1.48.0=h46256e1_0
  - llvm-openmp=19.1.7=h5048363_2
  - markupsafe=3.0.2=py313h46256e1_0
  - mpc=1.3.1=h46256e1_0
  - mpfr=4.2.1=h46256e1_0
  - mpmath=1.3.0=py313hecd8cb5_0
  - ncurses=6.5=h923df54_0
  - networkx=3.4.2=py313hecd8cb5_0
  - nomkl=3.0=0
  - numpy=2.3.1=py313h1a2ec72_0
  - numpy-base=2.3.1=py313hce0bb57_0
  - openssl=3.0.17=hee2dfae_0
  - opentelemetry-api=1.30.0=py313hecd8cb5_0
  - pip=25.3=pyhc872135_0
  - python=3.13.5=h81a7116_100_cp313
  - python_abi=3.13=0_cp313
  - pytorch=2.6.0=cpu_openblas_py313hfcfd596_6
  - readline=8.3=h49f2429_0
  - setuptools=72.1.0=py313hecd8cb5_0
  - sleef=3.5.1=h6c40b1e_2
  - sqlite=3.50.2=hc8b0dd6_1
  - sympy=1.13.3=py313hecd8cb5_1
  - tk=8.6.15=h3a5a201_0
  - wheel=0.45.1=py313hecd8cb5_0
  - wrapt=1.17.0=py313h46256e1_0
  - xz=5.6.4=h46256e1_1
  - zipp=3.21.0=py313hecd8cb5_0
  - zlib=1.2.13=h4b97444_1
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - coverage==7.13.0
      - deprecation==2.1.0
      - distro==1.9.0
      - fastapi==0.124.4
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - iniconfig==2.3.0
      - jiter==0.12.0
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - lance-namespace==0.3.1
      - lance-namespace-urllib3-client==0.3.1
      - lancedb==0.25.3
      - langchain==1.1.3
      - langchain-core==1.2.0
      - langchain-text-splitters==1.1.0
      - langgraph==1.0.5
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.3.0
      - langsmith==0.4.59
      - openai==2.11.0
      - orjson==3.11.5
      - ormsgpack==1.12.1
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pluggy==1.6.0
      - pyarrow==22.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pymupdf==1.26.7
      - pymupdf4llm==0.2.7
      - pytest==9.0.2
      - pytest-cov==7.0.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - sentence-transformers==5.2.0
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.50.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.2
      - uuid-utils==0.12.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websockets==15.0.1
      - xxhash==3.6.0
      - zstandard==0.25.0
prefix: /Users/dabsdamoon/miniconda3/envs/etl-pdf-pipeline
